- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix --indent 4 --no-sort-keys]
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-added-large-files
